2024-05-12 16:17:59 INFO open for scan: C:\Users\deeks\Documents\WayFAST\wandb\run-20240512_123639-ucn9ew0b\run-ucn9ew0b.wandb
2024-05-12 16:17:59 INFO watching files in: C:\Users\deeks\Documents\WayFAST\wandb\run-20240512_123639-ucn9ew0b\files
2024-05-12 16:17:59 INFO run started: ucn9ew0b with start time 1715531804.17611
2024-05-12 16:17:59 INFO saving file wandb-metadata.json with policy now
2024-05-12 16:17:59 INFO shutting down sender
2024-05-12 16:17:59 INFO Uploaded file C:\Users\deeks\AppData\Local\Temp\tmpagm9uhb1wandb\04626iv0-wandb-metadata.json
2024-05-12 16:18:00 INFO file/dir modified: C:\Users\deeks\Documents\WayFAST\wandb\run-20240512_123639-ucn9ew0b\files\output.log
2024-05-12 16:18:01 INFO file/dir modified: C:\Users\deeks\Documents\WayFAST\wandb\run-20240512_123639-ucn9ew0b\files\output.log
2024-05-12 16:18:03 INFO shutting down directory watcher
2024-05-12 16:18:03 INFO file/dir modified: C:\Users\deeks\Documents\WayFAST\wandb\run-20240512_123639-ucn9ew0b\files\output.log
2024-05-12 16:18:03 INFO scan: C:\Users\deeks\Documents\WayFAST\wandb\run-20240512_123639-ucn9ew0b\files
2024-05-12 16:18:03 INFO scan save: C:\Users\deeks\Documents\WayFAST\wandb\run-20240512_123639-ucn9ew0b\files\config.yaml config.yaml
2024-05-12 16:18:03 INFO scan save: C:\Users\deeks\Documents\WayFAST\wandb\run-20240512_123639-ucn9ew0b\files\output.log output.log
2024-05-12 16:18:03 INFO scan save: C:\Users\deeks\Documents\WayFAST\wandb\run-20240512_123639-ucn9ew0b\files\requirements.txt requirements.txt
2024-05-12 16:18:03 INFO scan save: C:\Users\deeks\Documents\WayFAST\wandb\run-20240512_123639-ucn9ew0b\files\wandb-metadata.json wandb-metadata.json
2024-05-12 16:18:03 INFO scan save: C:\Users\deeks\Documents\WayFAST\wandb\run-20240512_123639-ucn9ew0b\files\wandb-summary.json wandb-summary.json
2024-05-12 16:18:03 INFO shutting down file pusher
2024-05-12 16:18:03 INFO waiting for file pusher
2024-05-12 16:18:03 INFO Uploaded file C:\Users\deeks\Documents\WayFAST\wandb\run-20240512_123639-ucn9ew0b\files\config.yaml
2024-05-12 16:18:03 INFO Uploaded file C:\Users\deeks\Documents\WayFAST\wandb\run-20240512_123639-ucn9ew0b\files\output.log
2024-05-12 16:18:03 INFO Uploaded file C:\Users\deeks\Documents\WayFAST\wandb\run-20240512_123639-ucn9ew0b\files\requirements.txt
2024-05-12 16:18:03 INFO Uploaded file C:\Users\deeks\Documents\WayFAST\wandb\run-20240512_123639-ucn9ew0b\files\wandb-summary.json
2024-05-12 16:18:03 INFO file stream finish called
2024-05-12 16:18:04 INFO file stream finish is done
2024-05-12 16:20:37 INFO open for scan: C:\Users\deeks\Documents\WayFAST\wandb\run-20240512_121924-hw2kq5vs\run-hw2kq5vs.wandb
2024-05-12 16:20:37 ERROR 409 response executing GraphQL.
2024-05-12 16:20:37 ERROR {"errors":[{"message":"run hw2kq5vs was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-12 16:20:38 ERROR 409 response executing GraphQL.
2024-05-12 16:20:38 ERROR {"errors":[{"message":"run hw2kq5vs was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-12 16:20:41 ERROR 409 response executing GraphQL.
2024-05-12 16:20:41 ERROR {"errors":[{"message":"run hw2kq5vs was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-12 16:20:41 INFO Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\deeks\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\deeks\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\Users\deeks\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\deeks\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\deeks\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\deeks\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-05-12 16:20:45 ERROR 409 response executing GraphQL.
2024-05-12 16:20:45 ERROR {"errors":[{"message":"run hw2kq5vs was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-12 16:20:55 ERROR 409 response executing GraphQL.
2024-05-12 16:20:55 ERROR {"errors":[{"message":"run hw2kq5vs was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-12 16:21:12 ERROR 409 response executing GraphQL.
2024-05-12 16:21:12 ERROR {"errors":[{"message":"run hw2kq5vs was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-12 16:21:45 ERROR 409 response executing GraphQL.
2024-05-12 16:21:45 ERROR {"errors":[{"message":"run hw2kq5vs was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-12 16:23:00 ERROR 409 response executing GraphQL.
2024-05-12 16:23:00 ERROR {"errors":[{"message":"run hw2kq5vs was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-12 16:23:00 ERROR run hw2kq5vs was previously created and deleted; try a new run name (Error 409: Conflict)
Traceback (most recent call last):
  File "C:\Users\deeks\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\deeks\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2217, in upsert_run
    response = self.gql(
  File "C:\Users\deeks\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\internal\internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "C:\Users\deeks\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\deeks\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\Users\deeks\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\deeks\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\deeks\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\deeks\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\deeks\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\internal\sender.py", line 969, in send_run
    server_run = self._init_run(run, config_value_dict)
  File "C:\Users\deeks\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\internal\sender.py", line 1014, in _init_run
    server_run, inserted, server_messages = self._api.upsert_run(
  File "C:\Users\deeks\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\apis\normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run hw2kq5vs was previously created and deleted; try a new run name (Error 409: Conflict)
2024-05-12 16:23:00 INFO saving file wandb-metadata.json with policy now
2024-05-12 16:23:00 INFO saving file wandb-summary.json with policy end
2024-05-12 16:23:00 INFO handling exit code: 0
2024-05-12 16:23:00 INFO handling runtime: 241
2024-05-12 16:23:00 INFO saving file wandb-summary.json with policy end
2024-05-12 16:23:00 INFO send defer
2024-05-12 16:23:00 INFO handle sender defer: 0
2024-05-12 16:23:00 INFO send defer: 1
2024-05-12 16:23:00 INFO handle sender defer: 1
2024-05-12 16:23:00 INFO send defer: 2
2024-05-12 16:23:00 INFO handle sender defer: 2
2024-05-12 16:23:00 INFO send defer: 3
2024-05-12 16:23:00 INFO handle sender defer: 3
2024-05-12 16:23:00 INFO send defer: 4
2024-05-12 16:23:00 INFO handle sender defer: 4
2024-05-12 16:23:00 INFO send defer: 5
2024-05-12 16:23:00 INFO handle sender defer: 5
2024-05-12 16:23:00 INFO send defer: 6
2024-05-12 16:23:00 INFO handle sender defer: 6
2024-05-12 16:23:00 INFO send defer: 7
2024-05-12 16:23:00 INFO handle sender defer: 7
2024-05-12 16:23:00 INFO send defer: 8
2024-05-12 16:23:00 INFO handle sender defer: 8
2024-05-12 16:23:00 INFO Attempting to build job artifact
2024-05-12 16:23:00 INFO no source found
2024-05-12 16:23:00 INFO send defer: 9
2024-05-12 16:23:00 INFO handle sender defer: 9
2024-05-12 16:23:00 INFO send defer: 10
2024-05-12 16:23:00 INFO handle sender defer: 10
2024-05-12 16:23:00 INFO send defer: 11
2024-05-12 16:23:00 INFO handle sender defer: 11
2024-05-12 16:23:00 INFO send defer: 12
2024-05-12 16:23:00 INFO handle sender defer: 12
2024-05-12 16:23:00 INFO send defer: 13
2024-05-12 16:23:00 INFO handle sender defer: 13
2024-05-12 16:23:00 INFO send defer: 14
2024-05-12 16:23:00 INFO handle sender defer: 14
2024-05-12 16:23:00 INFO shutting down sender
